export type TicketStatus = "draft" | "active" | "ready_to_close" | "finalized" | "voided";
export type TicketDirection = "incoming" | "outgoing" | "transfer" | "processing";
export type WeighMethod = "double_weighing" | "preset_tare" | "manual_override_with_reason";

export interface TicketLineInput {
  product_id: string;
  crop_id?: string | null;
  batch_id?: string | null;
  lot_id?: string | null;
  supplier_lot?: string | null;
  warehouse_from_id?: string | null;
  warehouse_to_id?: string | null;
  quantity: number;
  uom?: string;
  unit_price?: number | null;
  amount?: number | null;
  notes?: string;
  net_line_weight_kg?: number | null;
  moisture_percent?: number | null;
  dockage_percent?: number | null;
  dirt_tare_percent?: number | null;
  class_grade?: string | null;
  variety_id?: string | null;
  reproduction_id?: string | null;
  batch_class?: string | null;
  operation_line_id?: string | null;
  mass_kg?: number | null;
  density_kg_per_l?: number | null;
  density_unit?: string | null;
  density_source?: string | null;
  density_verification_status?: string | null;
  density_verified_at?: string | null;
  unit_source?: string | null;
  unit_contract_version?: number | null;
}

export interface TicketInput {
  company_id: string;
  batch_id?: string | null;
  audit_json?: Record<string, unknown> | null;
  requires_review?: boolean;
  review_reason?: string | null;
  season_id?: string | null;
  ticket_type: string;
  op_type: string;
  direction: TicketDirection;
  source_kind: string;
  source_id?: string | null;
  destination_kind: string;
  destination_id?: string | null;
  processing_node_id?: string | null;
  field_id?: string | null;
  crop_structure_allocation_id?: string | null;
  warehouse_from_id?: string | null;
  warehouse_to_id?: string | null;
  supplier_id?: string | null;
  buyer_id?: string | null;
  supplier_document_no?: string | null;
  shipment_purpose?: string | null;
  destination_text?: string | null;
  external_document_no?: string | null;
  receipt_mode?: "weighbridge" | "direct" | string | null;
  supplier_receipt_kind?: "generic" | "agro_identity" | string | null;
  field_operation_type?: string | null;
  field_material_category?: string | null;
  disposal_category?: string | null;
  processing_point_from_id?: string | null;
  processing_point_to_id?: string | null;
  vehicle_id?: string | null;
  driver_id?: string | null;
  responsible_user_id?: string | null;
  created_by: string;
  created_by_person_id?: string | null;
  finalized_by_person_id?: string | null;
  weigh_method?: WeighMethod;
  gross_weight_kg?: number | null;
  tare_weight_kg?: number | null;
  notes?: string | null;
  linked_operation_id?: string | null;
  linked_request_id?: string | null;
  shift_id?: string | null;
}

export interface WeighingInput {
  weighing_no: 1 | 2;
  measured_weight_kg: number;
  measured_at?: string;
  device_source?: "scale_device" | "manual";
  operator_user_id?: string | null;
  comment?: string | null;
}

export interface WeighbridgeTicket {
  id: string;
  company_id: string;
  batch_id?: string | null;
  audit_json?: Record<string, unknown> | null;
  requires_review?: boolean;
  review_reason?: string | null;
  season_id?: string | null;
  company_name?: string | null;
  supplier_name_snapshot?: string | null;
  buyer_name_snapshot?: string | null;
  crop_name_snapshot?: string | null;
  variety_name_snapshot?: string | null;
  reproduction_name_snapshot?: string | null;
  created_by?: string | null;
  created_by_name_snapshot?: string | null;
  created_by_person_id?: string | null;
  void_reason?: string | null;
  correction_of_ticket_id?: string | null;
  replacement_ticket_id?: string | null;
  correction_reason?: string | null;
  correction_started_at?: string | null;
  correction_completed_at?: string | null;
  correction_of_ticket?: { id: string; ticket_no: string; status: TicketStatus } | null;
  replacement_ticket?: { id: string; ticket_no: string; status: TicketStatus } | null;
  correction_audit?: Array<{
    id: string;
    action: string;
    when_at: string;
    reason?: string | null;
    old_values?: Record<string, unknown> | null;
    new_values?: Record<string, unknown> | null;
  }>;
  field_name_snapshot?: string | null;
  warehouse_from_name_snapshot?: string | null;
  warehouse_to_name_snapshot?: string | null;
  vehicle_name_snapshot?: string | null;
  vehicle_plate_snapshot?: string | null;
  trailer_name_snapshot?: string | null;
  trailer_plate_snapshot?: string | null;
  driver_name_snapshot?: string | null;
  ticket_no: string;
  ticket_type: string;
  op_type: string;
  status: TicketStatus;
  shift_id?: string | null;
  direction: TicketDirection;
  source_kind: string;
  destination_kind: string;
  destination_id?: string | null;
  processing_node_id?: string | null;
  field_id?: string | null;
  warehouse_from_id?: string | null;
  warehouse_to_id?: string | null;
  supplier_id?: string | null;
  buyer_id?: string | null;
  supplier_document_no?: string | null;
  shipment_purpose?: string | null;
  destination_text?: string | null;
  external_document_no?: string | null;
  receipt_mode?: string | null;
  supplier_receipt_kind?: string | null;
  field_material_category?: string | null;
  disposal_category?: string | null;
  processing_point_from_id?: string | null;
  processing_point_to_id?: string | null;
  vehicle_id?: string | null;
  driver_id?: string | null;
  gross_weight_kg?: number | null;
  tare_weight_kg?: number | null;
  net_weight_kg?: number | null;
  weigh_method: WeighMethod;
  is_finalized: boolean;
  is_voided: boolean;
  finalized_at?: string | null;
  created_at: string;
  updated_at: string;
  notes?: string | null;
  crop_structure_allocation_id?: string | null;
  crop_structure_allocation_label?: string | null;
  lines?: Array<{
    id: string;
    product_id: string;
    product_name: string;
    quantity: number;
    uom: string;
    variety_id?: string | null;
    variety_name?: string | null;
    reproduction_id?: string | null;
    reproduction_name?: string | null;
    batch_class?: string | null;
    lot_id?: string | null;
    warehouse_from_id?: string | null;
    warehouse_to_id?: string | null;
    warehouse_from_name?: string | null;
    warehouse_to_name?: string | null;
    unit_price?: number | null;
    amount?: number | null;
    moisture_percent?: number | null;
    dockage_percent?: number | null;
    dirt_tare_percent?: number | null;
    product_name_snapshot?: string | null;
    variety_name_snapshot?: string | null;
    reproduction_name_snapshot?: string | null;
    notes?: string | null;
    operation_line_id?: string | null;
  }>;
}

export interface HarvestBatchSummary {
  id: string;
  batchCode: string;
  warehouseId: string;
  warehouseName: string;
  productId: string;
  productIds?: string[];
  productName: string;
  cropId: string | null;
  cropName: string;
  varietyId: string | null;
  varietyName: string;
  reproductionId: string | null;
  reproductionName: string;
  fieldId: string | null;
  fieldName: string;
  operationLineId: string | null;
  cropStructureLabel: string;
  seasonLabel: string;
  operationName: string;
  firstReceivedAt: string | null;
  lastReceivedAt: string | null;
  receivedKg: number;
  companyReceivedKg?: number;
  companyCurrentKg?: number;
  voidedKg?: number;
  removedKg: number;
  cleanMassKg: number;
  impurityPercent: number;
  processingInputKg?: number;
  processingOutputKg?: number;
  transferInKg?: number;
  transferOutKg?: number;
  writeoffKg?: number;
  issueKg?: number;
  otherAdjustmentKg?: number;
  reservedKg?: number;
  availableKg?: number;
  reconciliationDeltaKg?: number;
  harvestedAreaHa: number | null;
  grossYieldTPerHa: number | null;
  cleanYieldTPerHa: number | null;
  aggregateLot?: boolean;
  aggregateLotId?: string | null;
  tripCount?: number;
  reviewState?: "confirmed" | "requires_review";
  reviewReasons?: string[];
  fieldSummaries?: Array<{
    fieldId: string | null;
    fieldName: string;
    netWeightKg: number;
    tripCount: number;
  }>;
  tripBatches?: Array<{
    id: string;
    batchCode: string;
    ticketId: string | null;
    ticketNo: string;
    fieldId: string | null;
    fieldName: string;
    netWeightKg: number;
    moisturePercent: number | null;
    vehicleName?: string | null;
    driverName?: string | null;
    status: string;
    occurredAt: string | null;
  }>;
  outgoingDocuments?: Array<{
    id: string;
    label: string;
    quantityKg: number;
    occurredAt: string | null;
    warehouseName: string;
    actorName: string | null;
    sourceType: "weighbridge_ticket" | "processing_document" | "missing";
    sourceId: string | null;
    documentNo: string | null;
    ticketId: string | null;
    ticketNo: string | null;
    vehicleName: string | null;
    driverName: string | null;
    notes: string | null;
    processingDocument?: {
      id: string;
      transformationType: string;
      status: string;
      processingNodeName: string | null;
      startedAt: string | null;
      completedAt: string | null;
      sourceWarehouseName: string | null;
      inputBatchId: string | null;
      inputBatchCode: string | null;
      inputWeightKg: number;
      sourceTicketId: string | null;
      sourceTicketNo: string | null;
      createdByName: string | null;
      completedByName: string | null;
      note: string | null;
      outputs: Array<{
        lineType: string;
        batchClass: string;
        warehouseName: string | null;
        weightKg: number;
      }>;
    } | null;
  }>;
  tickets: Array<{
    id: string;
    ticketNo: string;
    operation: "harvest_incoming" | "weighbridge_impurities";
    netWeightKg: number;
    occurredAt: string | null;
  }>;
  movements: Array<{
    id: string;
    label: string;
    quantityKg: number;
    direction: "in" | "out";
    occurredAt: string | null;
    ticketNo: string;
  }>;
}

export interface WeighbridgeHumanOperator {
  id: string;
  name: string;
  has_pin?: boolean;
  pin_active?: boolean;
  locked_until?: string | null;
}

export interface WeighbridgeOperatorState {
  shift: Record<string, any> | null;
  unlocked: boolean;
  session_expires_at?: string | null;
  operator?: WeighbridgeHumanOperator | null;
  operators: WeighbridgeHumanOperator[];
}

export type TareVarianceConfirmation = {
  requires_confirmation: true;
  code: "tare_variance_confirmation_required";
  previous_tare_kg: number;
  current_tare_kg: number;
  difference_percent: number;
};
