export type TicketStatus = "draft" | "active" | "ready_to_close" | "finalized" | "voided";
export type TicketDirection = "incoming" | "outgoing" | "transfer" | "processing";
export type WeighMethod = "double_weighing" | "preset_tare" | "manual_override_with_reason";

export interface TicketLineInput {
  product_id: string;
  crop_id?: string | null;
  batch_id?: string | null;
  lot_id?: string | null;
  supplier_lot?: string | null;
  warehouse_from_id?: string | null;
  warehouse_to_id?: string | null;
  quantity: number;
  uom?: string;
  unit_price?: number | null;
  amount?: number | null;
  notes?: string;
  net_line_weight_kg?: number | null;
  moisture_percent?: number | null;
  dockage_percent?: number | null;
  dirt_tare_percent?: number | null;
  class_grade?: string | null;
  variety_id?: string | null;
  reproduction_id?: string | null;
  batch_class?: string | null;
  operation_line_id?: string | null;
  mass_kg?: number | null;
  density_kg_per_l?: number | null;
  density_unit?: string | null;
  density_source?: string | null;
  density_verification_status?: string | null;
  density_verified_at?: string | null;
  unit_source?: string | null;
  unit_contract_version?: number | null;
}

export interface TicketInput {
  company_id: string;
  season_id?: string | null;
  ticket_type: string;
  op_type: string;
  direction: TicketDirection;
  source_kind: string;
  source_id?: string | null;
  destination_kind: string;
  destination_id?: string | null;
  processing_node_id?: string | null;
  field_id?: string | null;
  crop_structure_allocation_id?: string | null;
  warehouse_from_id?: string | null;
  warehouse_to_id?: string | null;
  supplier_id?: string | null;
  buyer_id?: string | null;
  supplier_document_no?: string | null;
  shipment_purpose?: string | null;
  destination_text?: string | null;
  external_document_no?: string | null;
  receipt_mode?: "weighbridge" | "direct" | string | null;
  supplier_receipt_kind?: "generic" | "agro_identity" | string | null;
  field_operation_type?: string | null;
  field_material_category?: string | null;
  disposal_category?: string | null;
  processing_point_from_id?: string | null;
  processing_point_to_id?: string | null;
  vehicle_id?: string | null;
  driver_id?: string | null;
  responsible_user_id?: string | null;
  created_by: string;
  weigh_method?: WeighMethod;
  gross_weight_kg?: number | null;
  tare_weight_kg?: number | null;
  notes?: string | null;
  linked_operation_id?: string | null;
  linked_request_id?: string | null;
  shift_id?: string | null;
}

export interface WeighingInput {
  weighing_no: 1 | 2;
  measured_weight_kg: number;
  measured_at?: string;
  device_source?: "scale_device" | "manual";
  operator_user_id?: string | null;
  comment?: string | null;
}

export interface WeighbridgeTicket {
  id: string;
  company_id: string;
  season_id?: string | null;
  company_name?: string | null;
  ticket_no: string;
  ticket_type: string;
  op_type: string;
  status: TicketStatus;
  direction: TicketDirection;
  source_kind: string;
  destination_kind: string;
  destination_id?: string | null;
  processing_node_id?: string | null;
  field_id?: string | null;
  warehouse_from_id?: string | null;
  warehouse_to_id?: string | null;
  supplier_id?: string | null;
  buyer_id?: string | null;
  supplier_document_no?: string | null;
  shipment_purpose?: string | null;
  destination_text?: string | null;
  external_document_no?: string | null;
  receipt_mode?: string | null;
  supplier_receipt_kind?: string | null;
  field_material_category?: string | null;
  disposal_category?: string | null;
  processing_point_from_id?: string | null;
  processing_point_to_id?: string | null;
  vehicle_id?: string | null;
  driver_id?: string | null;
  gross_weight_kg?: number | null;
  tare_weight_kg?: number | null;
  net_weight_kg?: number | null;
  weigh_method: WeighMethod;
  is_finalized: boolean;
  is_voided: boolean;
  finalized_at?: string | null;
  created_at: string;
  updated_at: string;
  notes?: string | null;
  crop_structure_allocation_id?: string | null;
  crop_structure_allocation_label?: string | null;
  lines?: Array<{
    id: string;
    product_id: string;
    product_name: string;
    quantity: number;
    uom: string;
    variety_id?: string | null;
    variety_name?: string | null;
    reproduction_id?: string | null;
    reproduction_name?: string | null;
    batch_class?: string | null;
    lot_id?: string | null;
    warehouse_from_id?: string | null;
    warehouse_to_id?: string | null;
    warehouse_from_name?: string | null;
    warehouse_to_name?: string | null;
    unit_price?: number | null;
    amount?: number | null;
    notes?: string | null;
    operation_line_id?: string | null;
  }>;
}
