import assert from "node:assert/strict";
import { buildWarehouseFieldOrigins } from "../lib/warehouse/field-origins";
import { fieldSearchRank } from "../lib/fields/search-rank";
import { buildFieldHarvestProjection } from "../lib/fields/field-harvest";
const names = new Map([["f9", "9"], ["f19", "19"]]);
const ticket = { id: "t1", company_id: "c", season_id: "s", field_id: "f9", crop_structure_allocation_id: "a11", accepted_weight_kg: 814350, net_weight_kg: 900000, op_type: "harvest_incoming", status: "finalized", is_finalized: true, is_voided: false };
const areas = [{ id: "a11", field_id: "f9", area: 11 }, { id: "a34", field_id: "f9", area: 34 }, { id: "a12", field_id: "f9", area: 12 }, { id: "a20", field_id: "f9", area: 20 }];
const second = { ...ticket, id: "t2", crop_structure_allocation_id: "a34", accepted_weight_kg: 1294140 };
const bad = [{ ...ticket, id: "void", is_voided: true }, { ...ticket, id: "draft", status: "draft" }, { ...ticket, id: "replaced", replacement_ticket_id: "new" }];
const origins = buildWarehouseFieldOrigins([ticket, ticket, ...bad], areas, names);
assert.equal(origins.length, 1);
assert.equal(origins[0].netWeightKg, 814350);
assert.equal(origins[0].areaHa, 11);
assert.equal(origins[0].tripCount, 1);
assert.equal(origins[0].yieldTPerHa, 814.35 / 11);
const split = buildWarehouseFieldOrigins([{ ...ticket, accepted_weight_kg: 400000 }], areas, names, [ticket])[0];
assert.equal(split.netWeightKg, 400000);
assert.equal(split.yieldTPerHa, origins[0].yieldTPerHa, "field yield does not depend on destination warehouse");
const combined = buildWarehouseFieldOrigins([ticket, { ...ticket, id: "t3", accepted_weight_kg: 1000 }, second], areas, names)[0];
assert.equal(combined.areaHa, 45, "one plot area counted once across trips; unrelated plots excluded");
const unknown = buildWarehouseFieldOrigins([ticket, { ...second, crop_structure_allocation_id: null }], areas, names)[0];
assert.equal(unknown.areaHa, null); assert.equal(unknown.yieldTPerHa, null);
assert.equal(buildWarehouseFieldOrigins([{ ...ticket, field_id: "f19" }], areas, names)[0].yieldTPerHa, null, "foreign field area is not reused");
const projection = buildFieldHarvestProjection({ companyId: "c", seasonId: "s", fieldId: "f9", fieldAreaHa: 77, tickets: [ticket, second, ...bad], ledgerEntries: [], structureRows: areas });
assert.equal(projection.byAllocation.find(a => a.allocationId === "a11")?.yieldTPerHa, 74.032);
assert.equal(projection.byAllocation.find(a => a.allocationId === "a34")?.yieldTPerHa, 38.063);
assert.equal(projection.byAllocation.find(a => a.allocationId === "a12")?.acceptedMassKg, 0);
const found = ["19", "49", "9 герн", "29", "9", "90"].sort((a,b) => fieldSearchRank(a,"9") - fieldSearchRank(b,"9"));
assert.deepEqual(found.slice(0,2), ["9", "9 герн"]);
assert.equal(fieldSearchRank("Поле №9", "9"), 0);
console.log("PASS annotation regressions: plot mass/area, duplicate sources, voids/replacements, missing provenance, exact field search");
