import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { ImpuritySourcePicker } from "../components/weighbridge/impurity-source-picker";
import { isImpuritySourceSelectionBlocked } from "../lib/weighbridge/impurity-source-selection";

// tsx follows the repository's preserve JSX setting; server markup uses React.
(globalThis as typeof globalThis & { React: typeof React }).React = React;

const exactA = { key: "lot-a:field-49-elite", label: "Гала · Элита", description: "Остаток партии: 44,24 т", supportsSharedSelection: true };
const exactB = { key: "lot-b:field-49-first", label: "Гала · 1 репродукция", supportsSharedSelection: true };
const legacy = { key: "legacy:lot-c", label: "Балтик Роуз", supportsSharedSelection: false };
const options = [exactA, exactB, legacy];
assert.equal(isImpuritySourceSelectionBlocked([exactA.key], exactB, options), false);
assert.equal(isImpuritySourceSelectionBlocked([exactA.key], legacy, options), true);
assert.equal(isImpuritySourceSelectionBlocked([legacy.key], exactA, options), true);
assert.equal(isImpuritySourceSelectionBlocked([], legacy, options), false);
const render = (value: string[], rows = options) => renderToStaticMarkup(React.createElement(ImpuritySourcePicker, {options: rows, value, onChange: () => {}}));
assert.match(render([exactA.key]), /Гала · Элита/);
assert.match(render([exactA.key]), /value="Остаток партии: 44,24 т · Гала · Элита"/);
assert.match(render([exactA.key, exactB.key]), /Выбрано партий: 2 — выберите одну/);
assert.match(render([exactA.key, exactB.key], []), /Выбрано партий: 2 — выберите одну/);
assert.match(render([exactA.key], []), /Ранее выбранная партия/);
assert.doesNotMatch(render([exactA.key], []), /Выбранная партия сейчас недоступна|Не удалось подтвердить остатки|Обновляем остатки|Выбор сохранён/);
assert.match(render([exactA.key], []), /value="Ранее выбранная партия"/);
const picker = fs.readFileSync(path.join(process.cwd(), "components/weighbridge/impurity-source-picker.tsx"), "utf8");
const page = fs.readFileSync(path.join(process.cwd(), "app/(dashboard)/weighbridge/page.tsx"), "utf8");
assert.doesNotMatch(picker, /SheetContent|DialogContent|setDraftValue|commitPicker/);
assert.match(picker, /onChange\(\[option\.key\]\);\s*close\(\);/);
assert.doesNotMatch(picker, /normalizeImpuritySourceSelection|isImpuritySourceSelectionBlocked|Готово/);
assert.match(picker, /role="listbox"/);
assert.match(picker, /role="option"/);
assert.match(page, /hydratedWorkspaceKeyRef.current === universalWorkspacePersistKey\) return/);
assert.match(page, /Keep that party until it is changed by hand[\s\S]*?sourceBatchId: prev\.operationType === "impurity_removal" \? prev\.sourceBatchId : "",[\s\S]*?prev\.impuritySourceSelections\.map/);
assert.match(page, /description: `Остаток партии: \$\{formatWeightTonnes\(availableKg\)\}`/);
assert.match(page, /Выберите партию один раз — она сохранится до ручной смены/);
assert.doesNotMatch(page, /return harvestBatchDetailLoading \? "Данные партии ещё загружаются"/);
assert.match(page, /selectedImpuritySourceOptions.length !== impuritySourceSelectionKeys.length/);
assert.match(page, /harvestBatchDetailRequestedKey !==/);
console.log("P0 impurity controlled selection: 20 checks PASS (browser fixture covers interaction sequence)");
